### ISSUE TITLE
Implement an action: create function $function

### ISSUE THREAD

**Issue by php-coder** [php-coder/gtl#4]
This is a part of user story #1
- [x] #6 Parse action from string
- [x] #7 Produce internal representation
- [x] #8 Generate code from internal representation
- [x] #9 Parse code from string
- [x] #10 Write code to file
- [ ] #11 Read code from file
- [ ] Document
